### ISSUE TITLE
flinks.authorize having OpenSSL issue

### ISSUE THREAD

**Issue by designium** [phildionne/flinks#3]
Hi,

I'm trying to leverage Flinks gem and as I'm testing (localhost:3000), I am seeing the following error:

    flinks.authorize(login_id: "c1c14800-e22f-4963-6fe2-08d7798a1052")

    OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1))

Do you know what is the issue?

**Comment by phildionne** [comment]
It seems the https://sandbox.flinks.io/v3/ API endpoint, which is used by default by this gem, has been deprecated. I've reached out to the Flinks team to get an updated endpoint.

**Comment by designium** [comment]
@phildionne Thanks!

**Comment by designium** [comment]
@phildionne They did change their endpoint: 

flinks = Flinks.new(customer_id: "4338.....7ecb", api_endpoint: "https://toolbox-api.private.fin.ag/v3/")

This one works. So the new endpoint is toolbox-api.private.fin.ag/v3/

**Comment by phildionne** [comment]
Thanks! Handled in https://github.com/phildionne/flinks/commit/46f2279e3f8f7ad3601baf853dce42c960cb418e
